# This file contains values from Cookiecutter

default_context:
  project_name: "cumulusci_stripe"
  project_description: "A plugin for CumulusCI providing tasks for interacting with the Stripe API"
  organization: "MuseLab LLC"
  license: "BSD-3"
  minimal_python_version: 3.9
  github_name: "muselabdx"
  email: "opensource@muselab.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
